### ISSUE TITLE
Code availability

### ISSUE THREAD

**Issue by aryanasadianuoit** [bhheo/AB_distillation#5]
Hello,
I have recently read your paper. You have mentioned that your code is available, However, I can not find the code snippet of your new proposed loss functions and related experiments. Would you please help me with this issue?

Thank you

**Comment by bhheo** [comment]
My code is available on this repo. `cifar10_AB_distillation.py` and `MITscenes_AB_distillation.py` are codes for CIFAR-10 and MIT-scenes experiments. Since AB distillation requires feature maps on specific location and initialization stage for distillation, releasing the loss snippet has a risk of mis-implementing AB distillation. If you want codes for comparison, https://github.com/HobbitLong/RepDistiller implemented AB distillation with many other distillation methods. It might help you.
